language: go
sudo: required
go:
  - 1.10

addons:
  apt:
    sources:
    - sourceline: ppa:masterminds/glide
    packages:
    - glide

before_install:
  - export PATH=$PATH:$HOME/.local/bin

install:
  - glide install
  - go build