language: go
sudo: required
go:
  - 1.8.5

addons:
  apt:
    sources:
    - sourceline: ppa:masterminds/glide
    packages:
    - glide

before_install:
  - export PATH=$PATH:$HOME/.local/bin

install:
  - glide install

script:
  - make test
  - make build